# Generated by Django 4.2.7 on 2025-08-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('DIMENSIONAL', 'Dimensional'), ('VISUAL', 'Visual'), ('FUNCTIONAL', 'Funcional'), ('MATERIAL', 'Material'), ('ASSEMBLY', 'Ensamble'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('description', models.TextField(help_text='Descripción detallada del defecto')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_REPAIR', 'En Reparación'), ('REPAIRED', 'Reparado'), ('SCRAPPED', 'Desechado')], default='OPEN', max_length=20)),
                ('repair_notes', models.TextField(blank=True, help_text='Notas sobre la reparación realizada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_repairer', models.ForeignKey(blank=True, help_text='Reparador asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(help_text='Operación donde se detectó el defecto', on_delete=django.db.models.deletion.PROTECT, to='operations.operation')),
                ('reported_by', models.ForeignKey(help_text='Usuario que reportó el defecto', on_delete=django.db.models.deletion.PROTECT, related_name='reported_defects', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Usuario que resolvió el defecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_defects', to=settings.AUTH_USER_MODEL)),
                ('return_to_operation', models.ForeignKey(blank=True, help_text='Operación a la que regresa después de reparación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_serials', to='operations.operation')),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='serials.serialnumber')),
            ],
            options={
                'verbose_name': 'Defecto',
                'verbose_name_plural': 'Defectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
